### ISSUE TITLE
Add admin interface for manually creating DOIs

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/doi-service#1]
Needs to support:

1. Creating a new DOI with associated metadata, just like the web service
1. Creating a local record for an existing DOI (e.g. the DOI was registered through a separate process, and we want to add an entry in this system - this will be required in order to move the existing doi.ala.org.au into the doi-service).

**Comment by javier-molina** [comment]
This ticket also added the ability to register existing DOIs as per discussion with Mark

provider metadata and application metadata is implemented as text areas accepting a JSON document.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/doi-service/review/DS-CR-4
