### ISSUE TITLE
Create "My Downloads" page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#10]
This is a page for a logged-in user to see their DOIs (and downloads). See [GBIF version](https://www.evernote.com/l/AHfFvNLQ27FEm4z06vHjFwimvXRvh3X_kEYB/image.png) for inspiration.

Should be similar to home page (depends on #9) but should have option to edit (if allowed) and delete (if allowed) DOIs. 

Page should resolve via 2 URLs:
- ~~http://doi.ala.org.au/myDownloads~~ http://biocache.ala.org.au/download/mydownloads (or equiv)
- ~~http://doi.ala.org.au/userDownloads/{userId}~~ http://biocache.ala.org.au/download/userdownloads/{userId} (where {userId} is auth numeric ID)

UI should be similar to Gbif version (https://www.gbif.org/user/download):

![image](https://user-images.githubusercontent.com/532845/31754027-78002926-b4e0-11e7-8ca0-1f9a58f85fc2.png)

**Comment by javier-molina** [comment]
Will this page display all downloads for a user regardless of whether a DOI was requested for it or it will display only downloads with a DOI?

If it is the first I'm not sure we persist that information atm but Adam I'm pretty sure can answer that.

**Comment by nickdos** [comment]
Only DOI for now.

**Comment by javier-molina** [comment]
That makes things easier then.
Ta

**Comment by ansell** [comment]
The https://doi.ala.org.au/myDownloads page has been working for over 2 years.
