### ISSUE TITLE
DOI (download record) landing page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#11]
Page that resolves to a download DOI URL. 

 http://biocache.ala.org.au/download/{downloadID} or
http://biocache.ala.org.au/download/doi/{downloadID} ??

Base on GBIF version - e.g. https://www.gbif.org/occurrence/download/0006350-170714134226665

![image](https://user-images.githubusercontent.com/532845/31754084-df09221c-b4e0-11e7-9575-39829235042b.png)

Note the mouse-over on the dataset items - shows the DOI to each dataset, which we can provide from the Collectory (needs work in COllectory as the DOIs in there currently resolve to GBIF).

**Comment by ansell** [comment]
The landing page on doi.ala.org.au is redirected to from the official `doi.org` URL. Closing this based on that.
