### ISSUE TITLE
Download event triggers DOI

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#12]
Functionality to go into [biocache-service](https://github.com/AtlasOfLivingAustralia/biocache-service). See related issue #13.

- trigger DOI creation via a fault tolerant API call once download has completed and prior to sending an email to user (email should have DOI in it) (use JMS or equiv?)
- ZIP file to be retrieved from biocache server and stored on DOI server (ASW object store?)
- breakdown of datasets with counts to be stored (see GBIF DOI page & issue #11) 
- citation text to be stored 
- calling hub to be stored (so we can generate a new search URL)

Questions
- license to be provided by biocache-service or defaulted in DOI service?
- how to implement API call - straight HTTP or via queuing system, etc.?
- when to delete download file after DOI service has got a copy?
- whether to store DOI on biocache-service as well (not sure if there is a use-case)
- whether to use a DOI standard API (is there one?) in calling our DOI service so that if we implment a different DOI interface later on (or international/3rd parties wanting to use their own DOI service)?
- do we pass DOI onto logging API?

![imag1680](https://user-images.githubusercontent.com/8326394/31973769-72dda58a-b973-11e7-9939-499f529e92da.jpg)

**Comment by ansell** [comment]
Biocache downloads have triggered DOI minting for over 2 years now, so closing this. If there are outstanding parts, they should be tracked as new granular epics for a future development cycle.
