### ISSUE TITLE
Upgrade to Grails 3

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#14]
Check with Simon if we should convert to a different datasource (away from MongoDB) first.

**Comment by sbearcsiro** [comment]
Covered in 6a8eb4ea745b7245f9b62f7b4a607e7f425edb29 and f486b631cf050698d58aa60dd7be32986fc163c8, includes Postgres upgrade

**Comment by javier-molina** [comment]
This has been completed
