### ISSUE TITLE
Design and implement a fault tolerant pipeline

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#17]
Downloads should be run in a fault tolerant fashion (if not already in place).

Once DOI call is implemented the pipeline will look like this:

Prepare file
Mint DOI
Log DOI result?
Prepare and send e-mail

if a step fails due to an recoverable error (Unavailable system) it should be retried (indefinetely?). It is important to look for the usual suspects when implementing this, no poison messages, no lost messages (first thing that comes to mind is a messaging slstem but the idea is the same regardless of implementation)

Unrecoverable errors (Invalid metadata) should be reported to an admin with as much detail as possible while a generic email should be sent back to the requestor.

**Comment by nickdos** [comment]
@adam-collins biocache-service already uses JMS for a few things, doesn't it?

**Comment by ansell** [comment]
The current fault tolerance mechanism for DOI minting failing is to send direct HTTP download links in the biocache download emails.

**Comment by adam-collins** [comment]
see https://github.com/AtlasOfLivingAustralia/doi-service/issues/91
