### ISSUE TITLE
Convert existing API to RESTful

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/doi-service#19]
Presently doi-service exposes 3 API endpoints:

POST /api/v1/doi/mintDoi
GET /api/v1/doi/$id
GET /api/v1/doi/$id/download

Convert these into a more RESTful style, eg:

POST /api/doi
GET /api/doi/$id
GET /api/doi/$id/file

Include versioning via the Accept-Version header (Grails has built in support for this).

Keep the old URLs as redirects to the new methods where possible.

Note: due to the "/" embedded in DOIs, we're precluded from using the built in Grails "resources" URL mapping method as best I can tell.

**Comment by javier-molina** [comment]
Already in prod
