### ISSUE TITLE
Add email notification for certain errors

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/doi-service#2]
If the call to ANDS succeeds, but the system fails to save the DB record, then there would be a DOI without a landing page (unless a custom page was used). If this happens, then we need to send an email alert to ALA Support.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/doi-service/review/DS-CR-2

**Comment by javier-molina** [comment]
Under review. I can't create more labels though.

**Comment by javier-molina** [comment]
ngix was complaining when trying to run with ansible.

Visual code inspection looks fine and sensible.

**Comment by m-r-c** [comment]
What nginx errors did you get? Bear in mind that our current nginx role won't work if you run it against a target vm that already has apache installed (you can just stop apache and it then it should work, or start from a clean vm)

**Comment by javier-molina** [comment]
Apache already bound to port 80 was straightforward and yes stopping it was the only thing required.

This below is what I got afterwards, not sure exactly what the issue is.

```
RUNNING HANDLER [nginx : reload nginx] *****************************************
ok: [doi.vagrant1.ala.org.au] => {
    "msg": "checking config first"
}

RUNNING HANDLER [nginx : check nginx configuration] ****************************
fatal: [doi.vagrant1.ala.org.au]: FAILED! => {"changed": true, "cmd": "nginx -t", "delta": "0:00:00.009948", "end": "2016-04-11 05:49:32.336019", "failed": true, "rc": 1, "start": "2016-04-11 05:49:32.326071", "stderr": "nginx: [emerg] invalid number of arguments in \"ssl_certificate\" directive in /etc/nginx/sites-enabled/doi_service_https.conf:6\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [nginx : reload nginx - after config check] ********************

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @doi-service-standalone.retry

PLAY RECAP *********************************************************************
doi.vagrant1.ala.org.au    : ok=100  changed=19   unreachable=0    failed=1


```

Finally I have to run dos2unix on ala-install\ansible\roles\mongodb\files\disable-transparent-hugepages  (and add an empty line so git accepted it as change) as the windows new lines were breaking the script.

**Comment by javier-molina** [comment]
Yesterday evening the error went away. I didn't do any changes.
