### ISSUE TITLE
Add update / patch API endpoint

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/doi-service#20]
A DOI can have be updated, eg to change the URL to which is resolves.

Of the existing fields, determine which are mutable:
 - title
 - authors
 - description
 - dateMinted
 - provider
 - filename
 - contentType
 - providerMetadata
 - applicationMetadata
 - customLandingPageUrl
 - applicationUrl

And provide an update / patch endpoint that takes some JSON and replaces the fields in the DOI record with the new values.

Also check for changes to customLandingPageUrl and providerMetadata (and provider?), as these will also trigger an update call to the provider.

Finally, if the original mint call didn't include a file then this endpoint may also accept and store a file for the given DOI

**Comment by adam-collins** [comment]
closing
