### ISSUE TITLE
Admin page enhancements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#29]
- [ ] Add link to `/alaAdmin` near top of page
- [x] Add link to `/api` as  #above
- [x] Fix `/alaAdmin` page so it has header/footer
- [x] Add intermediate breadcrumb to DOI homepage (meta tag in head)
- [x] Links 1 & 2 in table are JSON but this is not obvious, so maybe add a hint (JSON icon or BS label maybe) about the links being JSON output???
- [x] Change plain box appearance of section under heading to use a BS "panel" or "well".
- [x] Change appearance of the "Using Amazon S3 storage at https://s3-ap-southeast-2.amazonaws.com, bucket: ala-doi-test" text to be a BS label, so its not confused with the link/s

**Comment by ansell** [comment]
One of the fixes may have been reverted since this was noted as fixed in 2017. Closing this as fixed, but feel free to open other issues to add the `/alaAdmin` link back if that is critical.
