### ISSUE TITLE
Update Ansible scripts for ala-hub and biocache-service for Ubuntu 16.x

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#34]
Bring up to date scripts for ansible-inventories/aws/aws-prod in order to deploy ala-hub and biocache-service in a new Ubuntu 16 box running Java 8.

biocache-b3.ala.org.au server will be replaced by this work.

**Comment by matthewandrews** [comment]
Specifically this would be Ubuntu 16.04 LTS.

It might be as simple as swapping out java for java8 and tomcat for tomcat7-java8 in the playbook.

**Comment by ansell** [comment]
The ansible scripts in ansible-inventories that are out of date have been removed. The remaining ansible scripts (bhub-b5/bws-b5/bdown-b5/test-bws-b5/test-bhub-b5) have been regularly run on production/test instances so they are confirmed to be 100% working at this point in time.
