### ISSUE TITLE
DOI Service, ALA Hub, Biocache Production release tasks

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#35]
This is to keep track of all the preparation for the upcoming DOI Production release.

What is neeed.

1. Ubuntu instance for DOI Service (Done)
2. Ubuntu instance for ala-hub, biocache (Not required)
3. Migrate only DOI https://doi.ala.org.au/ as a record in new DOI service
4. Add a link to myDownloads to the ALA profile page, once its live. https://auth.ala.org.au/userdetails/myprofile/

Go live!
Release DOI Service
Release biocache service
Release ala-hub

Questions
1. Do we need to migrate anything from biocache-b3.ala.org.au ?
2. What settings do we need for an S3 Bucket, who is providing those settings? (Done) (Matt and Patricia actioned this)

**Comment by matthewandrews** [comment]
I can organise the S3 bucket and permissions.  Presumably it would be public-read, private-write.

Just to clarify: this ala-hub and biocache instance is specifically for DOI? Do we get a significant advantage by separating it from doi service?

**Comment by javier-molina** [comment]
> I can organise the S3 bucket and permissions. Presumably it would be public-read, private-write.

private read and write, we will store sensitive records and doi service will be the front end to determine who can access the files.


>Just to clarify: this ala-hub and biocache instance is specifically for DOI? Do we get a significant advantage by separating it from doi service?

ala-hub and biocache are not specific for the doi service, these are the core ALA services and DOI service  will now become another core service added to the mix.

**Comment by nickdos** [comment]
Depending on the timing of the release, we could either do a minor update to DOI and then a major release with the distributed SOLR/Cassandra changes a but later. Or we could wait and release all at once. I'm thinking the former is safer and timing means we're not waiting extra weeks...

- ala-hub could be updated on the existing prod server or we could deploy to new server, possibly in a load-balanced pair (sharing these 2 servers with possible ala-bie and/or another prod front-end app)
- biocache-service could be manually updated on just solr-b4 as only downloads are affected and the other biocache-service (load-balanced) nodes can stay running as is
- DOI service to be installed on fresh server and we switch DNS. Needs to be on AWS for S3 bucket as we never tested the OpenStack version

**Comment by matthewandrews** [comment]
Yes this sounds good.  Given this is only going to be around for another week or few, I'd support just updating ala-hub on biocache-b3 and biocache-service on solr-b4.

**Comment by javier-molina** [comment]
We have a plan then.

When the time comes sounds like I need to prepare the release versions for ala-hub and biocache-service.

I can see both biocache-b3 and solr-b4 have java8 installed so nothing else required, I think.

**Comment by nickdos** [comment]
There are some minor changes to ala-hub that I need commit and and also release downloads-plugin. Once done, I'll deploy to biocache-test for a final sanity check.
