### ISSUE TITLE
Reuse production DOI

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#36]
See original e-mail below for offending record.

Tasks
1. Deactivate current record in ANDS
2. Once the ALA DOI Service goes live, find a candidate DOI to be created (PDF generation, etc) and manually create the DOI entry to match the ANDS DOI here. Update the ANDS DOI metadata with the manual entry and activate the record.

> Hi Michael,
 The DOI broken link checker ran on 2 Jan 2018 and reported broken links from ALA.
 Below is the DOI having issues and the link which was reported broken. Please review and update  the DOI as necessary. We will check for updates on the next scheduled check in April 2018 so > please spend time to resolve your broken links prior to that. You can request services@ands.org.au to re-run the tool against your DOIs at any time when the links have been updated or you can run the broken link tool from My DOIs (https://researchdata.ands.org.au/apps/mydois).
4/500s: DOI_ID: 10.4226/68/59eeda4cd94ad URL: https://devt.ala.org.au/doi-service/doi/94688376-feb4-4cd5-8b07-d4fcf3dceb3d Status HTTP/1.1 404 404
Judging from the title "Minting DOI TestGetting restarted with DOIs (Subtitle)" and the URL of the DOI, it seemed that this is a test DOI which was mistakenly minted using the prod appID. Can you please confirm.
If confirmed a test DOI and not used or shared anywhere, you have the option to re-use the DOI (update metadata and URL). Let us know if you have questions. Thank you.
Regards, Cel

![screen shot 2018-02-08 at 10 04 49 am](https://user-images.githubusercontent.com/8326394/35946378-a93c7d76-0cb7-11e8-93b0-fe896cf92bf6.png)

**Comment by javier-molina** [comment]
Step 1, DOI deactivated, complete

TODO execute step 2 when the time comes.

**Comment by adam-collins** [comment]
Does not seem to be time yet.
