### ISSUE TITLE
Push file from biocache service to DOI service instead of passing the url for it.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#37]
Currently the way Biocache and DOI services exchange the download zip file is as this:

1. Biocache service passes a url do DOI service to access the file
2. Doi service retrieves the file and stores it

With the imminent shutdown of the download urls in biocache this process has to change to this:

1. Biocache service will stream the file contents directly to DOI Service.

**Comment by ansell** [comment]
Done.
