### ISSUE TITLE
Ansible scripts

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/doi-service#4]
Nginx, tomcat, mongo, postfix.

Test (nci) & prod (aws) inventories.

**Comment by djtfmartin** [comment]
Just curious - why nginx instead of apache ?

**Comment by matthewandrews** [comment]
That was at my instigation - I'm shamelessly pushing the adoption of nginx in new apps where possible (we already use it for WordPress, Phylolink, the internal wiki, and a couple of others), as it's generally better performing (far more memory efficient) and simpler to configure. It's been the number one webserver among the top 1000 websites in the world for the last couple of years (including e.g. Netflix, WordPress.com, etc).

But of course happy to switch this back to Apache, discuss the broader approach, etc.

**Comment by djtfmartin** [comment]
Thanks @matthewandrews. Happy to go for the broader approach of moving to nginx and treating our use of apache as a legacy thing if you think this is the way to go.
