### ISSUE TITLE
Download DOI - add metadata for parent DOIs

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#43]
ALA data download DOIs have an associated list of data resources and datasets, etc. Many of the datasets, data resources, collections, etc., already have an associated DOI (minted by GBIF).

- [ ] send the list of parent DOIs in the metadata when minting the download DOI
- [ ] back-fill old/historical DOIs with dataset DOI links (both in metadata for DOI and in stored data in DOI-service)

Most of the code required for this issue will need to go in [biocache-service](https://github.com/AtlasOfLivingAustralia/biocache-service) but putting the issue in this repo for now. Please generate a specific issue in [biocache-service](https://github.com/AtlasOfLivingAustralia/biocache-service) when actioning this issue.

**Comment by adam-collins** [comment]
Is there still benefit in doing this?
