### ISSUE TITLE
Update ansible scripts to install elasticsearch 5.4.3

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/doi-service#46]
The latest version of the elasticsearch grails plugin requires elasticsearch 5.4.3, but our current ansible scripts install 1.x & the ansible scripts provided by es only install 6.x & 7.x

**Comment by ansell** [comment]
Done, but then we upgraded to es-7 anyway reusing the same ansible scripts as we use for other es-7 servers.
