### ISSUE TITLE
DOI API error responses should return JSON

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/doi-service#48]
Currently when a 4xx/5xx range HTTP error is thrown from any `/api` call the HTTP body is an HTML page (without the error text in the case of a 4xx error).  These endpoints should be updated to always respond with error messages encoded in a JSON doc / match the requested accept content type.

**Comment by adam-collins** [comment]
Updated to the error message to respect the `Accept` header. e.g. use `Accept: application/json` to receive error responses as JSON. Other than passing along DOI validation errors there will not be much information in the error response. 

Example response `{"message":"No doi was found for 1234"}`
