### ISSUE TITLE
https://doi.ala.org.au/myDownloads doesn't redirect to CAS

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/doi-service#49]
https://doi.ala.org.au/myDownloads should redirect to CAS when users are not logged-in, but currently it returns the following error message:

```
No UserId provided - check user is logged in and page is protected by AUTH
```

This is important as we are including this URL in emails, and users may not be logged in when they click on the link in their email and we should do the usual redirect through CAS that we do on the other compulsory authentication pages.

**Comment by nickdos** [comment]
Missing entry in `uriFilterPattern`, see https://github.com/AtlasOfLivingAustralia/doi-service/blob/master/grails-app/conf/application.yml#L147

**Comment by ansell** [comment]
This is now working on doi-test.ala.org.au for me. Closing and moving to `Ready for CAB` on the board.
