### ISSUE TITLE
Update api/doi endpoint documentation

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/doi-service#51]
POSTING to `api/doi` endpoint threw an error even though the documentation was followed. 
Debugging indicated missing properties in `providerMetadata` field. It will be good if this is reflected in the API doc and also the example updated.

```
{
...
    "providerMetadata": {
        "resourceType": "Text",
        "publisher": "test",
        "identifier": "test",
        "publicationYear": 2019,
        "authors": ["testing"]
    },
...
}

```

**Comment by adam-collins** [comment]
Updated the openapi documentation for the POST request with details present in code comments and information from the mintDoi page.
