### ISSUE TITLE
Add CSDM display template

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/doi-service#54]
CSDM has specific information that must be shown on DOI landing page. Create a custom template.

**Comment by temi** [comment]
Code review:
https://upsource.ala.org.au/doi-service/review/DS-CR-2
https://upsource.ala.org.au/spatial-hub/review/SH-CR-13
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/5d0ccc70dc40e67f03ceccb8d527a3e3d99f3244

**Comment by m-hope** [comment]
When this feature is implemented, the CSDM landing page template should include a URL link to the CSDM modelling tool hosted by the BCCVL.  The link to use is: [https://csdm-test.bccvl.org.au/datasets/import/ala?id=]_doi_id_ (where _doi_id_ is the DOI of the download).

**Comment by ansell** [comment]
@temi @m-hope This fix was released to production last night. nectar-spatial-test and csdm are not currently linked to production, but closing this as fixed based on it being in production now. Reopen if it is still an issue for CSDM users.

**Comment by m-hope** [comment]
Thanks Peter.
