### ISSUE TITLE
Allow configuration of default DOI minting provider 

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/doi-service#56]
The DOI minting provider is currently required to be passed to the doi-service. This requires client apps to be aware of the available providers. 

ALA client "apps" should be able to pass `ALA` as the provider and let the doi-service determine the host based on the configured default.

**Comment by nickdos** [comment]
Is this a dependency on PR #55? If so it will need to be included in the next release.

**Comment by Rita-C** [comment]
Bruce tested this one.
