### ISSUE TITLE
Styling broken in test site

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#57]
Header and footer are not showing up on test site.

May be related to ala-boostrap3-plugin version.

**Comment by brucehyslop** [comment]
The issue appears to be with the ansible configuration there was a change made (https://github.com/AtlasOfLivingAustralia/ala-install/commit/3434b26df72b73b9a39fa01b452647d906e456a2) that sets the default to `main` this should probably be `ala-main`

**Comment by nickdos** [comment]
Thanks @brucehyslop. The plugin _should_ provide a mapping from `main` to `ala-main` for backwards compatibility so not sure why it no longer works. Could you check that the client app hasn't included its own `main` layout, which might be taking precedence to the plugin version.

**Comment by brucehyslop** [comment]
the `application.yml` defaults the skin.layout to `ala-main`
however the ansible `doi-service-config.yml` template is 
```
skin:
  layout: {{ skin_layout | default('main') }}
```
my suspicion is that there is no `skin_layout` variable set so it's defaulting to `main`.

I'm not familiar with ansible so not 100% sure. The change to the ansible was reasonably recent (2020-04-28) and the only change I can see that would cause this behaviour. Prior to this change `ala-main` would have been used from `application.yml`.

**Comment by brucehyslop** [comment]
I've change ansible `doi-test` inventory to set the `site_layout=ala-main` rerun ansible-playbook for doc-test.

The style is now working on https://doi-test.ala.org.au/

@vjrj the default skin.layout does not match the layout defined in `application.yml`

**Comment by vjrj** [comment]
Thanks indeed @brucehyslop . It works for me also using development branch with `ala-main`.
