### ISSUE TITLE
Fix date created format on biocache template

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/doi-service#68]
The date created formatting on the biocache template shows "AM/PM", but it is not a localised date, it is a UTC+0 date. AM/PM should only be used where the date is localised to the particular user with a defined timezone.

https://github.com/AtlasOfLivingAustralia/doi-service/blob/fc753cfe4cdad465dcbd356153306a741aa86d87/grails-app/views/doiResolve/_biocache.gsp#L54

**Comment by brucehyslop** [comment]
It might be a better solution to remove the `format="yyyy-MM-dd h:mm a"` attribute from the `g:formatDate` taglib and define a format property in the MessageSource / ResourceBundle (i18n/*.properties file).

Either use:
 - the `default.date.format` property, or
 - define a customer property and set the `formatName` taglib attribute. 

see: https://docs.grails.org/3.1.1/ref/Tags/formatDate.html

**Comment by adam-collins** [comment]
To satisfy the issue the existing `doi.page.date.format=yyyy-MM-dd` messages.properties value. Where time is currently used `doi.page.time.format=h:mm a` is also available for change.
