### ISSUE TITLE
Hide download button when file not present

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/doi-service#72]
Applications like profiles mint DOIs without passing a file in the request. On the DOI detail page, the default metadata are shown with a download button. However, clicking the download button throws an error. Hiding the download button when file not present will provide a better user experience.

**Comment by adam-collins** [comment]
Errors are no longer produced when a download is unavailable.

- When a user is not authorised and Download is clicked an appropriate permissions related message is shown.
- When a download is no longer available an appropriate message is shown.

I would prefer seeing a disabled download button with the reason listed.

Leaving this for the UI/UX review.
