### ISSUE TITLE
Grails 4 and OIDC upgrade

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/doi-service#74]
- Upgrade to Grails 4.1.1
- Upgrade to postgresql 10
- OIDC and Java 11 upgrade

**Comment by yasima-csiro** [comment]
https://github.com/AtlasOfLivingAustralia/doi-service/tree/feature/grails4

**Comment by qifeng-bai** [comment]
I performed a functional tests doi-test passed on tests from Event pipelines and I confirmed the tests passed

**Comment by yasima-csiro** [comment]
Hi @qifeng-bai, getUserList API is deprecated now. https://auth.ala.org.au/userdetails/openapi#/users/getUserList

Might need to update the Biocache.

**Comment by yasima-csiro** [comment]
Testing results - https://csiroau.sharepoint.com/:f:/r/sites/AtlasofLivingAustralia/Shared%20Documents/Cloud%20Uplift/APIGateway+Cognito/Testing/DOI%20service?csf=1&web=1&e=5K6QDU

**Comment by qifeng-bai** [comment]
@yasima-csiro Thanks.  I will fellow up

**Comment by yasima-csiro** [comment]
Released with 2.0.0

**Comment by qifeng-bai** [comment]
@yasima-csiro I noticed getUserListByIds is also deprecated.  Would you please tell me what are the current APIs for those two?

**Comment by yasima-csiro** [comment]
Hi @qifeng-bai , You can find those info from here: https://docs.ala.org.au/#3-user-details
