### ISSUE TITLE
Register an existing DOI needs provider but UI field is disabled

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/doi-service#75]
Register an existing DOI needs provider to be supplied but UI field is disabled.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/72474143/185844201-0b7838c0-a649-4b8f-84f5-880f30535e64.png">

![image](https://user-images.githubusercontent.com/72474143/185844353-4c61ad7f-e7eb-445e-b50a-745990fb0eb1.png)

Because of this Register an existing DOI fails.

**Comment by yasima-csiro** [comment]
Hi @nickdos, I am thinking of removing the disabling of "Provider" field. I am not sure whether it is the correct solution for this. 
Would you be able to provide an input on this?

**Comment by nickdos** [comment]
Hi @yasima-csiro - I think we can remove this field - it was used when we were transitioning from ARDC to DataCite provider but ARDC is now not supported. So we can use DataCite as the only provider. 

@sbearcsiro - are there any possible LA use cases that might need the drop-down for other configurable providers?
