### ISSUE TITLE
Unable to download files for some newly minted DOIs in doi-test

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/doi-service#78]
Attempting to download some newly minted dois in doi-test throws either a 500 error (if authenticated) or redirects to `/downloadAuth` and shows `Too Many Redirects`(https://doi-test.ala.org.au/doi/2c8facc3-41ab-43f3-babd-c9e4d7548e3b/downloadAuth) error.  

The following is an example of a failing DOI -  https://doi-test.ala.org.au/doi/1b6601be-2470-41ab-ac47-d3f226f342c0 
THis DOI does not seem to fail on download though: https://doi-test.ala.org.au/doi/bb5397cd-cbf2-4e19-a8c0-3bad97dd8720 

Tested by missing `users/read` scopes to  doi-test OIDC service  and the application scope but the issues was not resolved. 
![Screen Shot 2022-10-26 at 9 53 40 am](https://user-images.githubusercontent.com/105408469/197901497-33ce6fd8-6fe8-448e-843c-096c27863897.png)
![Screen Shot 2022-10-26 at 9 53 25 am](https://user-images.githubusercontent.com/105408469/197901502-81ea99bb-c8ad-40f1-9e79-ae6aebb330f1.png)

**Comment by yasima-csiro** [comment]
Stacktrace

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/72474143/197905111-67b6fc01-f8c2-4b8a-a669-78b4b3548ea8.png">

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/doi-service/commit/9f491b908edcccdc53f82c9cf34ca807d595e1fc

**Comment by adam-collins** [comment]
ready for testing

**Comment by sughics** [comment]
Tested - Working as expected. Pending release before closing issue.

**Comment by sughics** [comment]
Released in 2.0.1
