### ISSUE TITLE
Show any DOI type in myDownloads

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/doi-service#80]
Design for My Downloads page is biased towards occurrence downloads and does not allow to show content for a different type of DOI

https://github.com/AtlasOfLivingAustralia/doi-service/blob/9f491b908edcccdc53f82c9cf34ca807d595e1fc/grails-app/controllers/au/org/ala/doi/ui/DoiResolveController.groovy#L60 

![Screen Shot 2022-11-21 at 2 15 43 pm](https://user-images.githubusercontent.com/8326394/202955698-96af8fb9-001f-45b0-b269-c1c1e89ddc8f.png)

![Screen Shot 2022-11-21 at 1 46 02 pm](https://user-images.githubusercontent.com/8326394/202954516-c42cdafe-56f2-431d-9d81-15930f697644.png)

Requirement:

Use index view to display generic and simple metadata for DOIs and includes all DOIs for a user not only those produced by biocache.

**Comment by adam-collins** [comment]
- What are the other applications that produce DOIs? 
  - CSDM (deprecated)
  - Phylolink (deprecated)
  - Events (no relevant because they not appear on on the `My Downloads` page)
