### ISSUE TITLE
DOI Downloads Update

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/doi-service#86]

**Comment by sat01a** [comment]
600 - In progress

10,800 - Completed.

**Comment by sat01a** [comment]
@Kylie to document and test.

**Comment by adam-collins** [comment]
600 or so remaining files backed up and removed, e.g. https://doi.ala.org.au/doi/68b7b12c-e53c-478f-9f06-404a5daae1e3

**Comment by kylie-m** [comment]
Tested, passed.  Confirming by clicking Download a 'not found' error is displayed
