### ISSUE TITLE
Create DOI home page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#9]
Currently http://doi.ala.org.au/ shows a single DOI record for BASE. Create a home page that provides a searchable list of DOIs as well as single sentence description.

- use i18n labels
- use Grails pagination and simple single input search on title and any text fields
- link to logged in user page (separate issue) - "My DOIs"

**Comment by ansell** [comment]
The front page is working, but it doesn't currently contain the link to "My DOIs". There is a link from the userdetails profile, which is the place we typically put these links. @nickdos Can this be closed despite there being no "My DOIs" link on the home page?

**Comment by nickdos** [comment]
Yes, closing
