### ISSUE TITLE
My Downloads - finished download still in table

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/doi-service#90]
A finished download was showing in the 'My Downloads' table with status 'running', hours after other larger downloads have finished and been cleared off the list. 

Unsure if an email was sent or if the download failed. 

![Image](https://github.com/AtlasOfLivingAustralia/doi-service/assets/90439797/03c285dd-e6cb-40e7-9fa6-00e253aad8fb)

-raised by @sat01a

**Comment by adam-collins** [comment]
Changed some code that may fix this issue https://github.com/AtlasOfLivingAustralia/biocache-service/pull/830

**Comment by adam-collins** [comment]
Because the above pull request may be delayed, the changes are also on pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/836
