### ISSUE TITLE
Duplicates in Datasets section of DOI page

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/doi-service#93]
The Datasets section on the DOI page lists any collectory entity (data resource, collection, institution, probably even data provider) associated with the downloaded data. This overstates the record count and looks confusing. 

eg here: https://doi.ala.org.au/doi/10.26197/ala.50e5b981-4703-48e3-95e7-ed67fe5924bd

Only list Data Resources with a record count. The counts will add up and the licenses should appear properly.

Maybe we should have a link on this page to "How to cite the ALA" as well? Or an actual citation someone can just copy and paste?

**Comment by adam-collins** [comment]
duplicate content of issue https://github.com/AtlasOfLivingAustralia/doi-service/issues/87
